export const CHANGE_UNIQUE_RIDES = 'CHANGE_UNIQUE_RIDES';
export const CHANGE_PEOPLE = 'CHANGE_PEOPLE';

export const START_COMPUTE = 'START_COMPUTE';
export const END_COMPUTE = 'END_COMPUTE';

export const TOGGLE_ADVANCED = 'TOGGLE_ADVANCED';
export const CHANGE_ITERATIONS = 'CHANGE_ITERATIONS';
export const CHANGE_MAX_LENGTH = 'CHANGE_MAX_LENGTH';
export const CHANGE_TRIM = 'CHANGE_TRIM';
